title = "Daniel Sada Caraveo | Software, Notes & Quantum"
baseURL = "https://danielsada.tech"
tags = ["portfolio", "developer", "blog", "danielsada", "tec de monterrey", "microsoft"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-43424010-8"
disqusShortname = "danielsada"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[permalinks]
  post = "/:title/"

[Params]
    tagline = "Software, Notes & Quantum"
    author = "Daniel Sada"
    description = "Computing Engineer, coffee enthusiast, productivity lover, quantum aprentice.I help people be more productive."
    logoBig = "/images/DanielSadaLogo.png"
    logoSmall = "/images/SadaLogo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/DanielSadaLogo.png"
    twitter = "danielsadac"
    linkedin = "danielsadac"
    github = "danielsada"
    facebook = "danielsada"
    email = "hello@danielsada.tech"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
    color = "#aaff00"
# [[menu.main]]
#     name = "Work"
#     url  = "/#work"
#     weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
