title = "Daniel Sada | Software, Notes & Quantum"
baseURL = "https://danielsada.mx"
tags = ["portfolio", "developer", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
<<<<<<< HEAD
googleAnalytics = "UA-43424010-8"
disqusShortname = "danielsada"
=======
googleAnalytics = ""
disqusShortname = ""
>>>>>>> c01267c... Removing gatsby, adding hugo
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[permalinks]
  post = "/:title/"

[Params]
    tagline = "Software, Notes & Quantum"
    author = "Daniel Sada"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
    logoBig = "/images/DanielSadaLogo.png"
    logoSmall = "/images/SadaLogo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "Danielsadamx"
    linkedin = "danielsadac"
    github = "danielsada"
    facebook = "danielsada"
    email = "yo@danielsada.mx"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
    color = "#aaff00"
# [[menu.main]]
#     name = "Work"
#     url  = "/#work"
#     weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4